import { describe, expect, it } from "vitest";
import { createEmptyDocument } from "../cad/document/CadDocument";
import { applyCadCommand, type CadCommandCall } from "../commands/cadCommandOperations";
import { evaluateParameters } from "../cad/parameters/expressionEvaluator";
import { solveSketch } from "../cad/sketch/SketchSolver";
import { detectProfiles } from "../cad/sketch/profileDetection";
import { validateDocument } from "../cad/document/validate";
import { serializeProject } from "../persistence/exportProject";
import { importProjectText } from "../persistence/importProject";

function fixture() {
  let document = createEmptyDocument("Semantic part");
  let aliases: Record<string, string> = {};
  const execute = (command: string, args: CadCommandCall["arguments"]) => {
    const applied = applyCadCommand(document, { command, arguments: args }, { aliases });
    document = applied.document; aliases = applied.aliases;
    return applied.result;
  };
  return { execute, document: () => document, aliases: () => aliases };
}
describe("stable semantic CAD commands", () => {
  it("creates parameter-driven profiles and explicit hole scopes without mutating inputs", () => {
    const part = fixture();
    const original = part.document();
    part.execute("cad.parameter.add", { name: "width", expression: "20mm", as: "width" });
    part.execute("cad.component.create", { name: "Plate", as: "plate" });
    part.execute("cad.sketch.create", { name: "Outline", plane: "XY", componentId: "$plate", as: "outline" });
    const rectangle = part.execute("cad.sketch.rectangle", { sketchId: "$outline", width: "width", height: "10", as: "rectangle" });
    expect(rectangle.pointIds).toHaveLength(4);
    expect(rectangle.entityIds).toHaveLength(4);
    expect(rectangle.profileIds).toHaveLength(1);
    const extrusion = part.execute("cad.feature.extrude", { sketchId: "$outline", distance: "5", profileId: "$rectangle.profile0", as: "base" });
    part.execute("cad.sketch.create", { name: "Drill", plane: "XY", componentId: "$plate", as: "drill" });
    part.execute("cad.sketch.point", { sketchId: "$drill", point: { x: "10", y: "5" }, as: "center" });
    part.execute("cad.feature.hole", { sketchId: "$drill", centerPointIds: ["$center"], targetBodyIds: ["$base.body"], diameter: "2mm", throughAll: true });
    expect(part.document().features[1]).toMatchObject({ type: "hole", targetBodyIds: [extrusion.bodyId] });
    expect(original.parameters).toEqual({});
    expect(original.features).toEqual([]);
    expect(validateDocument(part.document())).toEqual([]);
    const before = part.document();
    part.execute("cad.parameter.update", { parameterId: "$width", name: "plate_width", expression: "30mm" });
    const solved = solveSketch(part.document().sketches[part.aliases().outline], evaluateParameters(part.document().parameters).values);
    expect(detectProfiles(solved).profiles[0].bounds).toEqual({ minX: 0, maxX: 30, minY: 0, maxY: 10 });
    expect(before.parameters.width.expression).toBe("20mm");
    expect(part.document().parameters.plate_width.id).toBe(part.aliases().width);
    expect(importProjectText(serializeProject(part.document()))).toEqual(part.document());
  });
  it("supports shared point references, arcs, construction and driving dimensions", () => {
    const part = fixture();
    part.execute("cad.sketch.create", { name: "Arcs", plane: "XZ", as: "sketch" });
    part.execute("cad.sketch.point", { sketchId: "$sketch", point: { x: "0", y: "0" }, as: "center" });
    part.execute("cad.sketch.point", { sketchId: "$sketch", point: { x: "5", y: "0" }, as: "start" });
    part.execute("cad.sketch.point", { sketchId: "$sketch", point: { x: "0", y: "5" }, as: "end" });
    part.execute("cad.sketch.arc", { sketchId: "$sketch", centerPointId: "$center", startPointId: "$start", endPointId: "$end", as: "arc" });
    part.execute("cad.sketch.line", { sketchId: "$sketch", startPointId: "$end", endPointId: "$start", as: "line" });
    part.execute("cad.sketch.dimension", { sketchId: "$sketch", type: "radius", refs: ["$arc"], expression: "8mm" });
    let solved = solveSketch(part.document().sketches[part.aliases().sketch], {});
    expect(solved.arcs[0].radius).toBeCloseTo(8, 4);
    part.execute("cad.sketch.construction", { sketchId: "$sketch", entityIds: ["$line"], construction: true });
    solved = solveSketch(part.document().sketches[part.aliases().sketch], {});
    expect(solved.lines[0].construction).toBe(true);
    expect(detectProfiles(solved).profiles).toEqual([]);
  });
  it("deletes geometry with orphan points and dimensions, and protects dependencies", () => {
    const part = fixture();
    part.execute("cad.sketch.create", { name: "Outline", plane: "XY", as: "sketch" });
    const circle = part.execute("cad.sketch.circle", { sketchId: "$sketch", center: { x: "0", y: "0" }, radius: "5", as: "circle" });
    part.execute("cad.sketch.dimension", { sketchId: "$sketch", type: "diameter", refs: ["$circle"], expression: "12" });
    part.execute("cad.sketch.deleteEntities", { sketchId: "$sketch", entityIds: [circle.id!] });
    expect(part.document().sketches[part.aliases().sketch].entities).toEqual({});
    expect(part.document().sketches[part.aliases().sketch].dimensions).toEqual([]);
    part.execute("cad.sketch.rectangle", { sketchId: "$sketch", width: "20", height: "10" });
    part.execute("cad.feature.extrude", { sketchId: "$sketch", distance: "5", as: "base" });
    part.execute("cad.feature.fillet", { edges: [{ featureId: "$base", role: "endCapPerimeter" }], radius: "1mm" });
    const before = part.document();
    expect(() => part.execute("cad.feature.delete", { featureId: "$base" })).toThrow(/reference|owner|found/i);
    expect(part.document()).toBe(before);
    expect(() => part.execute("cad.feature.update", { featureId: "$base", radius: "1" })).toThrow("not a setting");
  });
  it("rejects unsafe, ambiguous, unsupported and invalid geometry before committing", () => {
    const part = fixture();
    const initial = part.document();
    expect(() => part.execute("cad.parameter.add", { name: "__proto__", expression: "1" })).toThrow(/parameter name/i);
    expect(() => part.execute("cad.component.create", { name: "No", unknown: true })).toThrow("unsupported");
    expect(() => part.execute("cad.sketch.create", { name: "No", plane: "face" })).toThrow(/one of XY/i);
    expect(() => part.execute("cad.parameter.add", { name: "bad", expression: "missing + 1" })).toThrow(/missing|unknown/i);
    expect(part.document()).toBe(initial);
    part.execute("cad.sketch.create", { name: "Outline", plane: "XY", as: "sketch" });
    expect(() => part.execute("cad.sketch.line", { sketchId: "$sketch" })).toThrow("exactly one of start");
    expect(() => part.execute("cad.sketch.rectangle", { sketchId: "$sketch", width: "0", height: "10" })).toThrow("positive");
    expect(() => part.execute("cad.sketch.line", { sketchId: "$sketch", start: { x: "0", y: "0" }, end: { x: "0", y: "0" } })).toThrow(/degenerate|length|line/i);
    expect(() => part.execute("cad.sketch.arc", { sketchId: "$sketch", center: { x: "0", y: "0" }, start: { x: "5", y: "0" }, end: { x: "0", y: "4" } })).toThrow(/share a positive radius/i);
    part.execute("cad.sketch.circle", { sketchId: "$sketch", center: { x: "0", y: "0" }, radius: "3" });
    part.execute("cad.sketch.circle", { sketchId: "$sketch", center: { x: "20", y: "0" }, radius: "3" });
    expect(() => part.execute("cad.feature.extrude", { sketchId: "$sketch", distance: "5" })).toThrow("Multiple profiles");
    expect(() => part.execute("cad.component.create", { name: "One", as: "sketch" })).toThrow("already bound");
    expect(() => part.execute("cad.component.rename", { componentId: "$unknown", name: "Bad" })).toThrow("Unknown plan reference");
  });
  it("keeps imperial scalar sizes and explicit lengths consistent", () => {
    let document = { ...createEmptyDocument(), unitSettings: { length: "in" as const, angle: "deg" as const }, units: "imperial" as const };
    const sketch = applyCadCommand(document, { command: "cad.sketch.create", arguments: { name: "Inches", plane: "YZ" } });
    document = sketch.document as typeof document;
    document = applyCadCommand(document, { command: "cad.sketch.rectangle", arguments: { sketchId: sketch.result.id!, width: "1", height: "25.4mm", origin: { x: "1", y: "0mm" } } }).document as typeof document;
    const solved = solveSketch(document.sketches[sketch.result.id!], {});
    expect(detectProfiles(solved).profiles[0].bounds).toEqual({ minX: 25.4, maxX: 50.8, minY: 0, maxY: 25.4 });
  });
  it("uses the GUI drawing helper with persistent sized center intent and no-op point reuse", () => {
    const part = fixture();
    part.execute("cad.parameter.add", { name: "width", expression: "20mm" });
    part.execute("cad.sketch.create", { name: "Drawn", plane: "XY", as: "sketch" });
    const rectangle = part.execute("cad.sketch.draw", { sketchId: "$sketch", tool: "rectangle", points: [{ x: 0, y: 0 }, { x: 10, y: 5 }], sizes: { width: "width", height: "10mm", rectangleMode: "center" }, as: "drawn" });
    let sketch = part.document().sketches[part.aliases().sketch];
    expect(rectangle.entityIds?.length).toBeGreaterThanOrEqual(4);
    expect(sketch.dimensions).toHaveLength(2);
    expect(detectProfiles(solveSketch(sketch, evaluateParameters(part.document().parameters).values)).profiles[0].bounds).toEqual({ minX: -10, maxX: 10, minY: -5, maxY: 5 });
    const corner = rectangle.pointIds![0];
    const before = part.document();
    const solved = solveSketch(sketch, evaluateParameters(before.parameters).values);
    part.execute("cad.sketch.draw", { sketchId: "$sketch", tool: "point", points: [{ x: solved.points[corner].x, y: solved.points[corner].y, pointId: corner }], construction: true });
    expect(part.document()).toBe(before);
    const id = Object.values(before.parameters)[0].id;
    part.execute("cad.parameter.update", { parameterId: id, expression: "30mm" });
    sketch = part.document().sketches[part.aliases().sketch];
    const profiles = detectProfiles(solveSketch(sketch, evaluateParameters(part.document().parameters).values)).profiles;
    expect(profiles[0].bounds.minX).toBeCloseTo(-15, 5);
    expect(profiles[0].bounds.maxX).toBeCloseTo(15, 5);
  });
  it("preserves shared endpoint identity and projects an unsnapped GUI arc endpoint", () => {
    const part = fixture();
    part.execute("cad.sketch.create", { name: "Drawn", plane: "XY", as: "sketch" });
    const first = part.execute("cad.sketch.draw", { sketchId: "$sketch", tool: "line", points: [{ x: 0, y: 0 }, { x: 5, y: 0 }] });
    expect(first.endpoint).toBeDefined();
    const second = part.execute("cad.sketch.draw", { sketchId: "$sketch", tool: "line", points: [{ ...first.endpoint! }, { x: 5, y: 5 }] });
    const sketch = part.document().sketches[part.aliases().sketch];
    expect(Object.values(sketch.entities).filter(entity => entity.type === "point")).toHaveLength(3);
    expect(second.pointIds).toHaveLength(1);
    part.execute("cad.sketch.draw", { sketchId: "$sketch", tool: "arc", points: [{ x: 0, y: 0 }, { x: 5, y: 0 }, { x: 0, y: 4 }], construction: true });
    const solved = solveSketch(part.document().sketches[part.aliases().sketch], {});
    expect(solved.arcs[0].radius).toBeCloseTo(5, 5);
    expect(solved.arcs[0].construction).toBe(true);
  });
  it("rejects incompatible boolean scopes and keeps immutable placements", () => {
    const part = fixture();
    part.execute("cad.component.create", { name: "Other", as: "other" });
    part.execute("cad.sketch.create", { name: "Outline", plane: "YZ", offset: "-2mm", as: "sketch" });
    part.execute("cad.sketch.rectangle", { sketchId: "$sketch", width: "10", height: "10" });
    part.execute("cad.feature.extrude", { sketchId: "$sketch", distance: "5", as: "base" });
    part.execute("cad.sketch.create", { name: "Other", componentId: "$other", plane: "XY", as: "other_sketch" });
    part.execute("cad.sketch.circle", { sketchId: "$other_sketch", center: { x: "0", y: "0" }, radius: "3" });
    expect(() => part.execute("cad.feature.extrude", { sketchId: "$other_sketch", distance: "5", operation: "cut", targetBodyIds: ["$base.body"] })).toThrow("in this component");
    const before = part.document();
    const translation = [10, 20, 30];
    part.execute("cad.component.place", { componentId: "$other", translation, rotation: [0, 0, 1] });
    translation[0] = 999;
    expect(before.components[part.aliases().other].placement).toBeUndefined();
    expect(part.document().components[part.aliases().other].placement!.translation).toEqual([10, 20, 30]);
  });
  it("keeps semantic rectangles orthogonal through driving dimension edits", () => {
    const part = fixture();
    part.execute("cad.sketch.create", { name: "Rectangle", plane: "XY", as: "sketch" });
    part.execute("cad.sketch.rectangle", { sketchId: "$sketch", width: "20mm", height: "10mm", as: "rectangle" });
    part.execute("cad.sketch.dimension", { sketchId: "$sketch", type: "length", refs: ["$rectangle.entity0"], expression: "30mm" });
    const sketch = part.document().sketches[part.aliases().sketch];
    const solved = solveSketch(sketch, {});
    solved.lines.forEach(line => {
      const horizontal = sketch.constraints.some(constraint => constraint.type === "horizontal" && constraint.entityIds.includes(line.id));
      expect(horizontal ? line.end.y - line.start.y : line.end.x - line.start.x).toBeCloseTo(0, 6);
    });
    const profile = detectProfiles(solved).profiles[0];
    expect(profile.bounds.maxX - profile.bounds.minX).toBeCloseTo(30, 5);
    expect(profile.bounds.maxY - profile.bounds.minY).toBeCloseTo(10, 5);
  });
});
