import type { CadDocument } from "../document/schema";
import type { RebuildResult } from "../worker/workerProtocol";
import type { NativeBore } from "../kernel/nativeDrawing";
import type { BoundingBox } from "../kernel/KernelAdapter";
import { bodyDisplayNames } from "../document/bodyDisplayNames";
import { assertDrawingMesh, DRAWING_VIEWS, drawingSection, orthographicSvg, projectDrawingPoint, type DrawingRect } from "./drawingGeometry";
export const DRAWING_MAX_BYTES = 8 * 1024 * 1024;
export interface DrawingBomRow { number: number; bodyId: string; name: string; quantity: 1; volumeMm3: number; solids: number }
export interface ShopDrawing { bodyId: string; name: string; bounds: BoundingBox; dimensions: [number, number, number]; bores: NativeBore[]; sectionHeight: number; sectionAreaMm2: number; bom: DrawingBomRow[]; warnings: string[]; svg: string; bomCsv: string }
export const escapeDrawingText = (text: string) => text.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[character]!);
const number = (value: number) => value.toFixed(3);
function csv(value: string) { const protectedValue = /^[\s]*[=+\-@]/.test(value) ? `'${value}` : value; return `"${protectedValue.replace(/"/g, '""')}"`; }
const text = (x: number, y: number, value: string, size = 13) => `<text x="${x}" y="${y}" font-size="${size}">${escapeDrawingText(value)}</text>`;
const truncate = (value: string, length: number) => value.length > length ? `${value.slice(0, length - 1)}…` : value;
function validBounds(bounds: BoundingBox) { return bounds && Array.isArray(bounds.min) && Array.isArray(bounds.max) && bounds.min.length === 3 && bounds.max.length === 3 && [...bounds.min, ...bounds.max].every(Number.isFinite) && bounds.min.every((value, axis) => value < bounds.max[axis]); }
export function buildShopDrawing(document: CadDocument, result: RebuildResult, bodyId: string, sectionHeight?: number): ShopDrawing {
  const mesh = result.meshes.find(mesh => mesh.bodyId === bodyId), geometry = result.nativeDrawingGeometry;
  if (!result.success || result.documentId !== document.id || !mesh || !geometry || !validBounds(geometry.bounds) || !result.meshes.length || result.meshes.some(mesh => mesh.geometrySource !== "opencascade" || !mesh.geometryAssertions?.valid || !Number.isFinite(mesh.geometryAssertions.volume) || !(mesh.geometryAssertions.volume > 0) || !Number.isSafeInteger(mesh.geometryAssertions.solidCount) || mesh.geometryAssertions.solidCount < 1)) throw new Error("Shop drawings require successful current native geometry and exact measurements. Repair or reselect the source part.");
  assertDrawingMesh(mesh);
  if (geometry.bores.length > 64 || geometry.bores.some(bore => ![bore.diameter, bore.length, ...bore.start, ...bore.direction].every(Number.isFinite) || bore.diameter <= 0 || bore.length <= 0 || Math.abs(Math.hypot(...bore.direction) - 1) > 1e-7)) throw new Error("Native bore drawing measurements are invalid or excessive.");
  const bounds = geometry.bounds, labels = bodyDisplayNames(document, result.bodies), name = labels[bodyId] ?? bodyId, dimensions = bounds.max.map((value, axis) => value - bounds.min[axis]) as [number, number, number];
  const height = sectionHeight ?? (bounds.min[2] + bounds.max[2]) / 2, section = drawingSection(mesh, bounds, height);
  const bom: DrawingBomRow[] = result.meshes.map((mesh, index) => ({ number: index + 1, bodyId: mesh.bodyId, name: labels[mesh.bodyId] ?? mesh.bodyId, quantity: 1, volumeMm3: mesh.geometryAssertions!.volume, solids: mesh.geometryAssertions!.solidCount }));
  const warnings = [...geometry.warnings];
  const bodyRowsHeight = bom.length * 34, boreRowsHeight = geometry.bores.length * 48, sheetHeight = Math.max(840, 210 + bodyRowsHeight + boreRowsHeight + warnings.length * 45);
  const top: DrawingRect = { x: 30, y: 80, width: 470, height: 285 }, front: DrawingRect = { x: 30, y: 390, width: 470, height: 265 }, right: DrawingRect = { x: 525, y: 80, width: 315, height: 285 }, cut: DrawingRect = { x: 525, y: 390, width: 315, height: 265 };
  const panel = (label: string, rect: DrawingRect, content: string) => `<g aria-label="${escapeDrawingText(label)}"><rect x="${rect.x}" y="${rect.y}" width="${rect.width}" height="${rect.height}" fill="none" stroke="#b8c6cb"/>${text(rect.x + 12, rect.y + 20, label)}${content}</g>`;
  const viewDimensions = (rect: DrawingRect, view: typeof DRAWING_VIEWS[keyof typeof DRAWING_VIEWS]) => {
    const low = projectDrawingPoint(bounds.min, bounds, view, rect), high = projectDrawingPoint(bounds.max, bounds, view, rect), baseline = rect.y + rect.height - 20, left = rect.x + 18;
    const paths = `M${low[0]},${low[1] + 4}V${baseline + 4}M${high[0]},${low[1] + 4}V${baseline + 4}M${low[0]},${baseline}H${high[0]}M${left - 4},${low[1]}H${low[0] - 4}M${left - 4},${high[1]}H${low[0] - 4}M${left},${low[1]}V${high[1]}`;
    const vertical = `${"XYZ"[view.yAxis]} ${number(dimensions[view.yAxis])} mm`;
    return `<path d="${paths}" fill="none" stroke="#4f6974" stroke-width="0.8"/>` + text((low[0] + high[0]) / 2 - 40, baseline + 15, `${"XYZ"[view.xAxis]} ${number(dimensions[view.xAxis])} mm`, 11) + `<text transform="translate(${left - 6},${(low[1] + high[1]) / 2}) rotate(-90)" text-anchor="middle" font-size="11">${escapeDrawingText(vertical)}</text>`;
  };
  const sectionPath = section.loops.map(loop => loop.map((point, index) => { const projected = projectDrawingPoint([point[0], point[1], height], bounds, DRAWING_VIEWS.top, cut); return `${index ? "L" : "M"}${projected[0].toFixed(2)},${projected[1].toFixed(2)}`; }).join("") + "Z").join("");
  let side = text(865, 100, "PROJECT PARTS LIST", 15) + text(865, 122, "One row per current body · quantity 1", 11), cursor = 148;
  for (const row of bom) { side += text(865, cursor, `${row.number}. ${truncate(row.name, 31)}`) + text(865, cursor + 15, `Qty 1 · ${number(row.volumeMm3)} mm³ · ${row.solids} solid(s)`, 11); cursor += 34; }
  side += text(865, cursor + 18, "VERIFIED INTERNAL BORES", 15); cursor += 42;
  if (!geometry.bores.length) { side += text(865, cursor, "No complete internal cylinders found", 11); cursor += 20; }
  for (const [index, bore] of geometry.bores.entries()) { side += text(865, cursor, `B${index + 1} · Ø${number(bore.diameter)} mm`) + text(865, cursor + 15, `Cylindrical wall length ${number(bore.length)} mm`, 11) + text(865, cursor + 29, `Axis ${bore.direction.map(number).join(", ")}`, 10); cursor += 48; }
  const sectionLineY = projectDrawingPoint([bounds.min[0], bounds.min[1], height], bounds, DRAWING_VIEWS.front, front)[1];
  const sectionLine = `<path d="M${front.x + 35},${sectionLineY}h${front.width - 70}" stroke="#487b8b" stroke-dasharray="8 4"/>` + text(front.x + 40, sectionLineY - 5, `A–A at Z ${number(height)} mm`, 11);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1188" height="${sheetHeight}" viewBox="0 0 1188 ${sheetHeight}" role="img" aria-label="${escapeDrawingText(`Shop drawing: ${name}`)}" data-body-id="${escapeDrawingText(bodyId)}"><title>${escapeDrawingText(`${document.name} — ${name}`)}</title><desc>Associative world-coordinate views. Dimensions use native bounds; outlines and section are tessellated. All dimensions are millimeters. Views fit independently.</desc><defs><pattern id="section-hatch" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="7" height="7" fill="#f5f8f7"/><path d="M0,0V7" stroke="#80979c" stroke-width="1"/></pattern></defs><rect width="1188" height="${sheetHeight}" fill="white"/><g fill="#172f39" font-family="Arial, sans-serif">${text(30, 35, truncate(document.name, 68), 23)}${text(30, 59, `${truncate(name, 65)} · dimensions in mm · each view fitted independently`, 13)}${panel("TOP · XY · from +Z", top, orthographicSvg(mesh, bounds, DRAWING_VIEWS.top, top) + viewDimensions(top, DRAWING_VIEWS.top))}${panel("FRONT · XZ · from −Y", front, orthographicSvg(mesh, bounds, DRAWING_VIEWS.front, front) + sectionLine + viewDimensions(front, DRAWING_VIEWS.front))}${panel("RIGHT · YZ · from +X", right, orthographicSvg(mesh, bounds, DRAWING_VIEWS.right, right) + viewDimensions(right, DRAWING_VIEWS.right))}${panel(`SECTION A–A · Z ${number(height)} mm`, cut, `<path d="${sectionPath}" fill="url(#section-hatch)" fill-rule="evenodd" stroke="#172f39" stroke-width="1.1"/>` + text(cut.x + 12, cut.y + cut.height - 14, `Mesh section area ${number(section.area)} mm²`, 11))}${side}${text(30, 697, "Native bounds dimensions; complete inward cylinders only. Bore lengths are wall lengths, not drilling depths.", 12)}${text(30, 718, "Outlines/hidden-edge visibility and sections are tessellated illustrations. No tolerance, GD&T or machining certification.", 12)}${text(30, 739, "Section A–A is a horizontal XY slice at the stated world Z; the cutting height is shown in the Front view.", 12)}${warnings.map((warning, index) => text(30, 770 + index * 20, truncate(warning, 150), 11)).join("")}${text(30, sheetHeight - 20, "PlainCAD · regenerated from the current project · complete body identities and names are in the CSV parts list", 11)}</g></svg>`;
  if (new TextEncoder().encode(svg).byteLength > DRAWING_MAX_BYTES) throw new Error("Drawing exceeds the 8 MiB SVG resource limit. Select a simpler part.");
  const bomCsv = ["Item,Part,Quantity,Volume mm3,Solids,Source body", ...bom.map(row => `${row.number},${csv(row.name)},1,${number(row.volumeMm3)},${row.solids},${csv(row.bodyId)}`)].join("\r\n");
  if (new TextEncoder().encode(bomCsv).byteLength > 128 * 1024) throw new Error("Parts list exceeds its 128 KiB resource limit. Shorten part names or identities.");
  return { bodyId, name, bounds, dimensions, bores: geometry.bores, sectionHeight: height, sectionAreaMm2: section.area, bom, warnings, svg, bomCsv };
}
