import { expect, test, type Page } from "@playwright/test";
import { aiPlatePlan } from "../src/tests/fixtures/aiPlan";
import { aiSnapshot } from "./aiAcceptanceHelpers";
async function nativeVolume(page: Page, expected: number) {
  await expect(async () => {
    const state = await aiSnapshot(page);
    expect(state.status).toBe("succeeded");
    expect(state.result?.documentId).toBe(state.document.id);
    expect(state.result?.meshes).toHaveLength(1);
    const mesh = state.result!.meshes[0];
    expect(mesh.geometrySource).toBe("opencascade");
    expect(mesh.geometryAssertions).toMatchObject({ valid: true, solidCount: 1 });
    expect(mesh.geometryAssertions!.volume).toBeCloseTo(expected, 5);
  }).toPass({ timeout: 30000 });
}
test("canvas conversation creates a part then halves thickness locally with native geometry, stable IDs and one-step undo/redo", async ({ page }) => {
  test.setTimeout(120000);
  let requests = 0;
  await page.route("**/api/ai/status", route => route.fulfill({ json: { providers: ["anthropic", "openai", "google"].map(id => ({ id, label: id, available: true, model: "test-model" })) } }));
  await page.route("**/api/ai/generate", route => { requests++; return route.fulfill({ json: { plan: aiPlatePlan } }); });
  await page.goto("/");
  await expect(page.locator(".rebuild-pill")).toHaveText("succeeded");
  await page.getByRole("button", { name: "New project", exact: true }).click();
  await expect.poll(async () => (await aiSnapshot(page)).status).toBe("succeeded");
  await page.getByRole("button", { name: "Open AI assistant", exact: true }).click();
  const panel = page.getByRole("region", { name: "AI modeling assistant" });
  const prompt = panel.getByLabel("What would you like to make?"), generate = panel.getByRole("button", { name: "Generate preview", exact: true });
  await prompt.fill(aiPlatePlan.summary);
  await generate.click();
  const apply = panel.getByRole("button", { name: "Apply AI component", exact: true });
  await expect(apply).toBeEnabled({ timeout: 60000 });
  await apply.click();
  const volume = 12000 - Math.PI * 2 ** 2 * 5;
  await nativeVolume(page, volume);
  const created = await aiSnapshot(page);
  expect(requests).toBe(1);
  const thickness = Object.values(created.document.parameters).find(parameter => parameter.name.endsWith("_thickness"))!;
  expect(thickness.expression).toBe("5mm");
  // A local follow-up requires no model configuration or extra provider request.
  await panel.getByLabel("AI model", { exact: true }).fill("");
  await prompt.fill("halve thickness");
  await expect(generate).toBeEnabled();
  await generate.click();
  const applyEdit = panel.getByRole("button", { name: "Apply AI parameter edits", exact: true });
  await expect(applyEdit).toBeEnabled({ timeout: 60000 });
  expect((await aiSnapshot(page)).document).toEqual(created.document);
  await expect(async () => {
    const preview = await page.evaluate(async () => {
      const path = "/src/state/aiCanvasPreview.ts";
      return (await import(path)).useAiCanvasPreview.getState().preview?.result;
    });
    expect(preview?.meshes).toHaveLength(1);
    expect(preview?.meshes[0].geometryAssertions).toMatchObject({ valid: true, solidCount: 1 });
    expect(preview?.meshes[0].geometrySource).toBe("opencascade");
    expect(preview?.meshes[0].geometryAssertions?.volume).toBeCloseTo(volume / 2, 5);
  }).toPass({ timeout: 30000 });
  await expect(page.locator(".viewer-canvas canvas")).toHaveCount(1);
  await expect.poll(async () => page.evaluate(async () => {
    const path = "/src/viewer/viewerDiagnostics.ts";
    const preview = (await import(path)).inspectViewer()?.aiPreview;
    if (!preview?.meshes[0] || preview.mode !== "after") return undefined;
    return Math.max(...preview.meshes[0].positions.filter((_value: number, index: number) => index % 3 === 2));
  })).toBe(2.5);
  expect(requests).toBe(1);
  await applyEdit.click();
  await nativeVolume(page, volume / 2);
  const edited = await aiSnapshot(page);
  expect(edited.document.id).toBe(created.document.id);
  expect(edited.document.features.map(feature => feature.id)).toEqual(created.document.features.map(feature => feature.id));
  expect(edited.result!.meshes[0].bodyId).toBe(created.result!.meshes[0].bodyId);
  expect(edited.document.parameters[thickness.name].id).toBe(thickness.id);
  expect(edited.document.parameters[thickness.name].expression).toBe("2.5mm");
  expect(edited.past).toBe(created.past + 1);
  expect(requests).toBe(1);
  await prompt.fill("undo that"); await generate.click();
  await nativeVolume(page, volume);
  expect((await aiSnapshot(page)).document).toEqual(created.document);
  await prompt.fill("redo that"); await generate.click();
  await nativeVolume(page, volume / 2);
  expect((await aiSnapshot(page)).document).toEqual(edited.document);
  expect(requests).toBe(1);
  const manualThickness = page.getByRole("textbox", { name: `Parameter ${thickness.name} expression`, exact: true });
  await manualThickness.fill("3mm"); await manualThickness.press("Enter");
  await nativeVolume(page, volume * 3 / 5);
  const manual = await aiSnapshot(page);
  await prompt.fill("undo that"); await generate.click();
  await expect(panel).toContainText("latest AI change cannot be undone");
  expect((await aiSnapshot(page)).document).toEqual(manual.document);
  expect((await aiSnapshot(page)).past).toBe(manual.past);
  expect(requests).toBe(1);
});

test("fix that repairs a failed native recipe using its original request and diagnostic, and a replaced project cannot send stale repair context", async ({ page }) => {
  test.setTimeout(180000);
  const broken = { ...aiPlatePlan, parameters: aiPlatePlan.parameters.map(parameter => parameter.name === "diameter" ? { ...parameter, value: 500 } : parameter) };
  const requests: Array<{ prompt: string; history: Array<{ role: string; content: string }> }> = [];
  await page.route("**/api/ai/status", route => route.fulfill({ json: { providers: ["anthropic", "openai", "google"].map(id => ({ id, label: id, available: true, model: "test-model" })) } }));
  await page.route("**/api/ai/generate", route => {
    requests.push(route.request().postDataJSON());
    return route.fulfill({ json: { plan: requests.length === 2 ? aiPlatePlan : broken } });
  });
  await page.goto("/");
  await expect(page.locator(".rebuild-pill")).toHaveText("succeeded");
  await page.getByRole("button", { name: "New project", exact: true }).click();
  await expect.poll(async () => (await aiSnapshot(page)).status).toBe("succeeded");
  await page.getByRole("button", { name: "Open AI assistant", exact: true }).click();
  const panel = page.getByRole("region", { name: "AI modeling assistant" });
  const prompt = panel.getByLabel("What would you like to make?"), generate = panel.getByRole("button", { name: "Generate preview", exact: true });
  const original = "Create a 60 by 40 by 5mm mounting plate with a bore. Keep thickness editable.";
  const before = await aiSnapshot(page);
  await prompt.fill(original); await generate.click();
  await expect(panel.getByRole("alert").last()).toBeVisible({ timeout: 60000 });
  const diagnostic = (await panel.getByRole("alert").last().textContent())!;
  expect(diagnostic.length).toBeGreaterThan(10);
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  expect((await aiSnapshot(page)).past).toBe(before.past);
  await expect(panel.getByRole("button", { name: "Apply AI component", exact: true })).toBeDisabled();
  await prompt.fill("fix that"); await expect(generate).toBeEnabled(); await generate.click();
  const apply = panel.getByRole("button", { name: "Apply AI component", exact: true });
  await expect(apply).toBeEnabled({ timeout: 60000 });
  expect(requests).toHaveLength(2);
  expect(requests[1].prompt).toContain(original);
  expect(requests[1].prompt).toContain(diagnostic.slice(0, 100));
  expect(JSON.parse(requests[1].history.at(-1)!.content)).toEqual(broken);
  expect((await aiSnapshot(page)).past).toBe(before.past);
  await apply.click();
  await nativeVolume(page, 12000 - Math.PI * 2 ** 2 * 5);
  expect((await aiSnapshot(page)).past).toBe(before.past + 1);
  // Capture another failure, then replace the project before requesting its repair.
  await page.getByRole("button", { name: "New project", exact: true }).click();
  await expect.poll(async () => (await aiSnapshot(page)).status).toBe("succeeded");
  await prompt.fill(original); await generate.click();
  await expect(panel.getByRole("alert").last()).toBeVisible({ timeout: 60000 });
  expect(requests).toHaveLength(3);
  await page.getByRole("button", { name: "New project", exact: true }).click();
  await expect.poll(async () => (await aiSnapshot(page)).status).toBe("succeeded");
  const replaced = await aiSnapshot(page);
  await prompt.fill("fix that");
  await expect(generate).toBeEnabled();
  await generate.click();
  await expect(panel).toContainText("There is no current failed AI proposal to repair.");
  expect(requests).toHaveLength(3);
  expect((await aiSnapshot(page)).document).toEqual(replaced.document);
  expect((await aiSnapshot(page)).past).toBe(replaced.past);
});
