import { expect, test } from "@playwright/test";
import { aiSnapshot } from "./aiAcceptanceHelpers";
import { workbenchTaskFixture } from "./workbenchTaskFixtures";

test("AI sketch proposal uses the existing drawing canvas, preserves camera/history and validates native Apply/Undo", async ({ page }) => {
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles({ name: "Editable.pcaddoc", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(workbenchTaskFixture("Extrude"))) });
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(3072, 5)).toPass();
  await page.getByRole("button", { name: "Section XY plane, 8 entities", exact: true }).click();
  await page.getByRole("button", { name: "Edit sketch canvas", exact: true }).click();
  const canvas = page.getByRole("group", { name: "Sketch drawing canvas", exact: true });
  const view = await canvas.getAttribute("viewBox"), bounds = await canvas.boundingBox(), before = await aiSnapshot(page);
  await page.getByRole("button", { name: "Open AI assistant", exact: true }).click();
  const panel = page.getByLabel("Sketch refinement", { exact: true });
  await panel.getByLabel("Sketch refinement request").fill("make this rectangle 20 x 14 mm");
  await panel.getByRole("button", { name: "Preview sketch refinement" }).click();
  await expect(panel.getByLabel("Sketch refinement status")).toContainText("Native refinement preview ready");
  const overlay = canvas.getByLabel("Proposed AI sketch geometry");
  await expect(overlay.locator("line")).toHaveCount(4);
  expect(await overlay.evaluate(group => { const points = Array.from(group.querySelectorAll("line")).flatMap(line => [Number(line.getAttribute("x1")), Number(line.getAttribute("x2"))]); return Math.max(...points) - Math.min(...points); })).toBeCloseTo(20, 5);
  expect(await overlay.evaluate(group => { const points = Array.from(group.querySelectorAll("line")).flatMap(line => [Number(line.getAttribute("y1")), Number(line.getAttribute("y2"))]); return Math.max(...points) - Math.min(...points); })).toBeCloseTo(14, 5);
  await expect(panel.locator("svg, canvas")).toHaveCount(0);
  expect(await canvas.getAttribute("viewBox")).toBe(view);
  expect(await canvas.boundingBox()).toEqual(bounds);
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  await page.getByRole("button", { name: "Before sketch", exact: true }).click();
  await expect(overlay).toHaveCount(0);
  await page.getByRole("button", { name: "After sketch", exact: true }).click();
  await expect(overlay).toBeAttached();
  await panel.getByRole("button", { name: "Cancel refinement" }).click();
  await expect(overlay).toHaveCount(0);
  expect((await aiSnapshot(page)).past).toBe(before.past);
  await panel.getByRole("button", { name: "Preview sketch refinement" }).click();
  await expect(overlay).toBeAttached();
  await page.getByRole("button", { name: "Close AI assistant", exact: true }).click();
  await expect(overlay).toHaveCount(0);
  await page.getByRole("button", { name: "Open AI assistant", exact: true }).click();
  await panel.getByLabel("Sketch refinement request").fill("make this rectangle 20 x 14 mm");
  await panel.getByRole("button", { name: "Preview sketch refinement" }).click();
  await expect(overlay).toBeAttached();
  await panel.getByRole("button", { name: "Apply sketch refinement" }).click();
  await expect(overlay).toHaveCount(0);
  await expect(async () => {
    const current = await aiSnapshot(page);
    expect(current.result?.meshes[0]).toMatchObject({ geometrySource: "opencascade", geometryAssertions: { valid: true, solidCount: 1 } });
    expect(current.result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(2240, 3);
    expect(current.past).toBe(before.past + 1);
  }).toPass();
  await page.getByRole("button", { name: "Close AI assistant", exact: true }).click();
  await page.getByRole("button", { name: "Finish Sketch", exact: true }).click();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(3072, 5)).toPass();
});
