import { expect, test } from "@playwright/test";
import { aiSnapshot } from "./aiAcceptanceHelpers";
import { workbenchTaskFixture } from "./workbenchTaskFixtures";

test("sketch repair and same-sketch follow-up stay on the main drawing and require fresh Apply consent", async ({ page }) => {
  const requests: Array<{ prompt: string; history: unknown[]; sketchContext: unknown }> = [];
  await page.route("**/api/ai/status", route => route.fulfill({ json: { providers: ["anthropic", "openai", "google"].map(id => ({ id, label: id, available: true, model: `configured-${id}` })) } }));
  await page.route("**/api/ai/sketch", async route => {
    requests.push(route.request().postDataJSON());
    await route.fulfill({ json: { proposal: { summary: "Resize the rectangle", warnings: [], actions: [{ kind: "rectangle", width: requests.length === 1 ? "-1mm" : requests.length === 2 ? "20mm" : "22mm", height: "14mm" }] } } });
  });
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles({ name: "Editable.pcaddoc", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(workbenchTaskFixture("Extrude"))) });
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(3072, 5)).toPass();
  await page.getByRole("button", { name: "Section XY plane, 8 entities", exact: true }).click();
  await page.getByRole("button", { name: "Edit sketch canvas", exact: true }).click();
  await page.getByRole("button", { name: "Open AI assistant", exact: true }).click();
  await page.getByLabel("Sketch refinement method").selectOption("provider");
  const prompt = page.getByLabel("Provider sketch request");
  const generate = page.getByRole("button", { name: "Generate AI sketch preview", exact: true });
  const consent = page.getByRole("checkbox", { name: /^Allow sending/ });
  await prompt.fill("fix that");
  await generate.click();
  await expect(page.getByLabel("Provider sketch refinement status")).toContainText("Which issue should I fix");
  expect(requests).toHaveLength(0);
  await prompt.fill("Make the rectangle 20 x 14 mm");
  await expect(page.getByText("Configured model: configured-anthropic")).toBeVisible();
  await consent.check();
  await generate.click();
  await expect(page.getByRole("alert")).toContainText("positive");
  const before = await aiSnapshot(page);
  await prompt.fill("repair this");
  await generate.click();
  const apply = page.getByRole("button", { name: "Apply AI sketch refinement", exact: true });
  await expect(apply).toBeEnabled();
  expect(requests[1].prompt).toContain("Make the rectangle 20 x 14 mm");
  expect(requests[1].prompt).toContain("positive");
  await expect(page.getByLabel("Proposed AI sketch geometry")).toBeVisible();
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  await apply.click();
  await expect(consent).not.toBeChecked();
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(2240, 3)).toPass();
  await prompt.fill("Now make it 22 x 14 mm");
  await expect(generate).toBeDisabled();
  expect(requests).toHaveLength(2);
  await consent.check();
  await generate.click();
  await expect(apply).toBeEnabled();
  expect(requests[2].history).toHaveLength(4);
  expect(requests[2].sketchContext).not.toEqual(requests[1].sketchContext);
  expect((await aiSnapshot(page)).past).toBe(before.past + 1);
  expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(2240, 3);
  await page.getByRole("button", { name: "Cancel AI sketch refinement", exact: true }).click();
  await expect(page.getByLabel("Proposed AI sketch geometry")).toHaveCount(0);
});
