import { expect, test } from "@playwright/test";
import { aiSnapshot } from "./aiAcceptanceHelpers";
import { buildContextualConstraint } from "../src/cad/sketch/contextualConstraints";
import { detectProfiles } from "../src/cad/sketch/profileDetection";
import { evaluateExpressionRef, evaluateParameters } from "../src/cad/parameters/expressionEvaluator";
import { workbenchTaskFixture } from "./workbenchTaskFixtures";

test("selected sketch relation previews native geometry, cancels, applies once, and rejects stale selection", async ({ page }) => {
  const fixture = workbenchTaskFixture("Extrude");
  const sketch = Object.values(fixture.sketches)[0];
  const line = Object.values(sketch.entities).find((entity) => entity.type === "line")!;
  if (line.type !== "line") throw new Error("Expected a line fixture");
  const endpoint = sketch.entities[line.endPointId];
  if (endpoint.type !== "point") throw new Error("Expected a point fixture");
  sketch.constraints.push({ id: "context_fixed_origin", type: "fixed", entityIds: [], pointIds: [line.startPointId] });
  sketch.entities[endpoint.id] = { ...endpoint, y: { expression: "3mm", unit: "mm" } };
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles({ name: "relations.pcaddoc", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(fixture)) });
  await expect(async () => expect((await aiSnapshot(page)).status).toBe("succeeded")).toPass();
  await page.getByRole("button", { name: "Section XY plane, 8 entities", exact: true }).click();
  await page.getByRole("button", { name: "Edit sketch canvas", exact: true }).click();
  await page.getByRole("button", { name: "Draw tool: select", exact: true }).click();
  await page.getByLabel("Selected sketch item", { exact: true }).selectOption(line.id);
  const panel = page.getByRole("region", { name: "Selected geometry relations", exact: true });
  await expect(panel.getByRole("button", { name: "Preview Horizontal" })).toBeVisible();
  const source = await aiSnapshot(page);
  const expectedPlan = buildContextualConstraint(fixture, sketch.id, [line.id], "horizontal");
  const profile = detectProfiles(expectedPlan.solved).profiles[0];
  if (!profile || !profile.outerLoop.segments) throw new Error("Expected an analytic polygon profile");
  const area = Math.abs(profile.outerLoop.segments.reduce((sum, segment) => sum + segment.start.x * segment.end.y - segment.end.x * segment.start.y, 0)) / 2;
  const extrude = fixture.features[0];
  if (extrude.type !== "extrude") throw new Error("Expected an extrude fixture");
  const depth = evaluateExpressionRef(extrude.distance, { parameters: evaluateParameters(fixture.parameters).values }).quantity?.value;
  if (!depth) throw new Error("Expected positive depth");
  const expectedVolume = area * depth;
  await panel.getByRole("button", { name: "Preview Horizontal" }).click();
  await expect(panel.getByLabel("Constraint preview status")).toContainText("Native constraint preview ready");
  expect((await aiSnapshot(page)).document).toEqual(source.document);
  await panel.getByRole("button", { name: "Cancel relation" }).click();
  expect((await aiSnapshot(page)).past).toBe(source.past);
  await panel.getByRole("button", { name: "Preview Horizontal" }).click();
  await expect(panel.getByRole("button", { name: "Apply relation" })).toBeEnabled();
  await page.getByLabel("Selected sketch item", { exact: true }).selectOption(endpoint.id);
  await expect(panel.getByRole("button", { name: "Apply relation" })).toHaveCount(0);
  expect((await aiSnapshot(page)).past).toBe(source.past);
  expect((await aiSnapshot(page)).document).toEqual(source.document);
  await page.getByLabel("Selected sketch item", { exact: true }).selectOption(line.id);
  await panel.getByRole("button", { name: "Preview Horizontal" }).click();
  await expect(panel.getByRole("button", { name: "Apply relation" })).toBeEnabled();
  await panel.getByRole("button", { name: "Apply relation" }).click();
  await expect(async () => {
    const state = await aiSnapshot(page), mesh = state.result!.meshes[0];
    expect(state.status).toBe("succeeded");
    expect(mesh).toMatchObject({ geometrySource: "opencascade", geometryAssertions: { valid: true, solidCount: 1 } });
    expect(mesh.geometryAssertions?.volume).toBeCloseTo(expectedVolume, 4);
    expect(mesh.geometryAssertions?.volume).not.toBeCloseTo(source.result!.meshes[0].geometryAssertions!.volume, 3);
    expect(state.past).toBe(source.past + 1);
    const solved = state.result!.solvedSketches![sketch.id].lines.find((candidate) => candidate.id === line.id)!;
    expect(solved.start.y).toBeCloseTo(solved.end.y, 6);
    expect(Object.keys(state.document.sketches[sketch.id].entities)).toEqual(Object.keys(source.document.sketches[sketch.id].entities));
  }).toPass();
  await page.getByRole("button", { name: "Finish Sketch", exact: true }).click();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(source.result!.meshes[0].geometryAssertions!.volume, 4)).toPass();
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(expectedVolume, 4)).toPass();
});
