import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { aiSnapshot, stlSignedVolume } from "./aiAcceptanceHelpers";
import { workbenchTaskFixture } from "./workbenchTaskFixtures";

for (const provider of ["anthropic", "openai", "google"]) test(`${provider} sketch conversation validates native geometry before explicit Apply`, async ({ page }, info) => {
  const requests: Array<Record<string, unknown>> = [];
  let proposalNumber = 0, release: (() => void) | undefined;
  await page.route("**/api/ai/status", (route) => route.fulfill({ json: { providers: ["anthropic", "openai", "google"].map((id) => ({ id, label: id, available: true, model: "test-model" })) } }));
  await page.route("**/api/ai/sketch", async (route) => {
    requests.push(route.request().postDataJSON()); proposalNumber += 1;
    if (proposalNumber === 1) { await route.fulfill({ json: { proposal: { summary: "What width and height should this rectangle have?", warnings: [], actions: [] } } }); return; }
    if (proposalNumber === 2) await new Promise<void>((resolve) => { release = resolve; });
    await route.fulfill({ json: { proposal: { summary: "Make it 60 × 40 mm", warnings: [], actions: [{ kind: "rectangle", width: "60mm", height: "40mm" }] } } });
  });
  const fixture = workbenchTaskFixture("Extrude");
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles({ name: "rectangle.pcaddoc", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(fixture)) });
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(3072, 5)).toPass();
  await page.getByRole("button", { name: "Section XY plane, 8 entities", exact: true }).click();
  await page.getByRole("button", { name: "Edit sketch canvas", exact: true }).click();
  await page.getByRole("button", { name: "Open AI assistant", exact: true }).click();
  await page.getByLabel("Sketch refinement method").selectOption("provider");
  const panel = page.getByLabel("Provider sketch refinement", { exact: true });
  await panel.getByLabel("Sketch AI provider").selectOption(provider);
  const prompt = panel.getByLabel("Provider sketch request"), generate = panel.getByRole("button", { name: "Generate AI sketch preview" });
  await prompt.fill("Please make this rectangle larger");
  await expect(generate).toBeDisabled();
  expect(requests).toHaveLength(0);
  await panel.getByRole("checkbox").check();
  const before = await aiSnapshot(page);
  await generate.click();
  await expect(panel.getByLabel("Provider sketch refinement status")).toContainText("clarification");
  await expect(panel.getByRole("button", { name: "Apply AI sketch refinement" })).toHaveCount(0);
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  await prompt.fill("Use 60 by 40 millimeters");
  await generate.click();
  await expect.poll(() => requests.length).toBe(2);
  await panel.getByRole("button", { name: "Cancel AI sketch refinement" }).click();
  release!();
  await expect(panel.getByLabel("Provider sketch refinement status")).toContainText("canceled");
  await expect(panel.getByRole("button", { name: "Apply AI sketch refinement" })).toHaveCount(0);
  expect((await aiSnapshot(page)).past).toBe(before.past);
  await generate.click();
  await expect(panel.getByLabel("Provider sketch refinement status")).toContainText("Native AI sketch preview ready");
  await expect(panel).toContainText("19200.000 mm³");
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  expect(requests[2].history).toEqual([{ role: "user", content: "Please make this rectangle larger" }, { role: "assistant", content: JSON.stringify({ summary: "What width and height should this rectangle have?", warnings: [], actions: [] }) }]);
  expect(requests[2].provider).toBe(provider);
  expect(requests[2].sketchContext).toMatchObject({ bindingPolicy: "preserve", selectedIds: [] });
  expect(Object.keys(requests[2])).toEqual(["provider", "model", "prompt", "history", "sketchContext"]);
  await panel.getByRole("button", { name: "Apply AI sketch refinement" }).click();
  await expect(async () => {
    const current = await aiSnapshot(page), mesh = current.result?.meshes[0];
    expect(current.status).toBe("succeeded"); expect(current.past).toBe(before.past + 1);
    expect(mesh).toMatchObject({ geometrySource: "opencascade", geometryAssertions: { valid: true, solidCount: 1 } });
    expect(mesh?.geometryAssertions?.volume).toBeCloseTo(19200, 4);
    expect(mesh!.bounds.max[0] - mesh!.bounds.min[0]).toBeCloseTo(60, 5);
    expect(mesh!.bounds.max[1] - mesh!.bounds.min[1]).toBeCloseTo(40, 5);
    expect(mesh!.bounds.max[2] - mesh!.bounds.min[2]).toBeCloseTo(8, 5);
    expect(current.document.features[0].id).toBe(before.document.features[0].id);
  }).toPass();
  await page.getByRole("button", { name: "Close AI assistant", exact: true }).click();
  await page.getByRole("button", { name: "Finish Sketch", exact: true }).click();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(3072, 5)).toPass();
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(19200, 4)).toPass();
  const saving = page.waitForEvent("download"); await page.getByRole("button", { name: "Save project", exact: true }).click();
  const path = info.outputPath(`${provider}-edit.pcaddoc`); await (await saving).saveAs(path);
  const saved = JSON.parse(await readFile(path, "utf8")), priorOpen = await aiSnapshot(page);
  await page.locator('input[type="file"]').setInputFiles(path);
  await expect.poll(async () => (await aiSnapshot(page)).session).toBeGreaterThan(priorOpen.session);
  await expect(async () => { const reopened = await aiSnapshot(page); expect(reopened.document.sketches).toEqual(saved.sketches); expect(reopened.result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(19200, 4); }).toPass();
  const exporting = page.waitForEvent("download");
  await page.getByRole("navigation", { name: "Main CAD commands", exact: true }).getByRole("button", { name: "Export STL", exact: true }).click();
  const stl = info.outputPath(`${provider}-edit.stl`); await (await exporting).saveAs(stl);
  expect(stlSignedVolume(await readFile(stl))).toBeCloseTo(19200, 1);
});

test("provider shared-parameter edits require explicit choice and preserve sketch bindings in native geometry", async ({ page }) => {
  const fixture = workbenchTaskFixture("Extrude"), sketch = Object.values(fixture.sketches)[0];
  const line = Object.values(sketch.entities).find((entity) => entity.type === "line")!;
  fixture.parameters.width = { id: "width_parameter", name: "width", expression: "24mm", value: 24, unit: "mm" };
  sketch.solveMode = "driving";
  for (const entity of Object.values(sketch.entities)) {
    if (entity.type === "point" && entity.x.expression === "24mm") entity.x = { expression: "width", unit: "mm" };
  }
  sketch.dimensions = [{ id: "width_dimension", type: "length", entityIds: [line.id], expression: { expression: "width", unit: "mm" } }];
  await page.route("**/api/ai/status", (route) => route.fulfill({ json: { providers: ["anthropic", "openai", "google"].map((id) => ({ id, label: id, available: true, model: "test-model" })) } }));
  await page.route("**/api/ai/sketch", (route) => route.fulfill({ json: { proposal: { summary: "Change shared width to 36mm", warnings: ["Other parts using width will rebuild"], actions: [{ kind: "parameter", id: "width_parameter", expression: "36mm" }] } } }));
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles({ name: "bound-rectangle.pcaddoc", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(fixture)) });
  await expect(async () => expect((await aiSnapshot(page)).result?.meshes[0].geometryAssertions?.volume).toBeCloseTo(3072, 5)).toPass();
  await page.getByRole("button", { name: "Section XY plane, 8 entities", exact: true }).click();
  await page.getByRole("button", { name: "Edit sketch canvas", exact: true }).click();
  await page.getByRole("button", { name: "Open AI assistant", exact: true }).click();
  await page.getByLabel("Sketch refinement method").selectOption("provider");
  const panel = page.getByLabel("Provider sketch refinement", { exact: true });
  await panel.getByLabel("Provider sketch request").fill("Change shared width to 36mm");
  await panel.getByRole("checkbox").check();
  const before = await aiSnapshot(page);
  await panel.getByRole("button", { name: "Generate AI sketch preview" }).click();
  await expect(panel.getByRole("alert")).toContainText("explicitly");
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  await panel.getByLabel("AI sketch binding policy").selectOption("parameter:width_parameter");
  await panel.getByRole("button", { name: "Generate AI sketch preview" }).click();
  await expect(panel.getByLabel("Provider sketch refinement status")).toContainText("Native AI sketch preview ready");
  await expect(panel.getByLabel("AI proposed sketch changes")).toContainText("sketch:");
  await panel.getByRole("button", { name: "Apply AI sketch refinement" }).click();
  await expect(async () => {
    const state = await aiSnapshot(page), mesh = state.result?.meshes[0];
    expect(state.status).toBe("succeeded"); expect(state.past).toBe(before.past + 1);
    expect(mesh).toMatchObject({ geometrySource: "opencascade", geometryAssertions: { valid: true, solidCount: 1 } });
    expect(mesh?.geometryAssertions?.volume).toBeCloseTo(4608, 5);
    expect(state.document.parameters.width.expression).toBe("36mm");
    expect(state.document.sketches[sketch.id].dimensions[0].expression.expression).toBe("width");
  }).toPass();
});
