import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { createBoxTemplate, createMountingPlateTemplate } from "../src/templates/templates";
import { aiSnapshot, stlSignedVolume } from "./aiAcceptanceHelpers";

test.use({ storageState: { cookies: [], origins: [] } });
test("inserts independent editable parts at their source origin, preserves undo, saves/reopens and exports real native STL", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator(".rebuild-pill")).toHaveText("succeeded");
  const initialSession = (await aiSnapshot(page)).session;
  const target = createBoxTemplate(), source = createMountingPlateTemplate();
  await page.locator('input[type="file"]').first().setInputFiles({ name: "box.pcaddoc", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(target)) });
  await expect(async () => {
    const snapshot = await aiSnapshot(page);
    expect(snapshot.session).toBeGreaterThan(initialSession);
    expect(snapshot.document.id).toBe(target.id);
    expect(snapshot.status).toBe("succeeded");
    expect(snapshot.result).toMatchObject({ documentId: target.id, success: true });
    expect(snapshot.result!.meshes).toHaveLength(1);
    expect(snapshot.result!.meshes[0].geometryAssertions!.volume).toBeCloseTo(80000, 6);
  }).toPass({ timeout: 30000 });
  const before = await aiSnapshot(page);
  await page.getByText("New part", { exact: true }).click();
  await page.getByRole("button", { name: "Insert a reusable part", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Insert reusable part", exact: true });
  await expect(dialog).toBeVisible();
  await dialog.getByLabel("Source project").setInputFiles({ name: "plate.pcaddoc", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(source)) });
  await expect(dialog.getByRole("button", { name: "Insert components", exact: true })).toBeEnabled();
  await dialog.getByRole("button", { name: "Insert components", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(async () => {
    const snapshot = await aiSnapshot(page);
    expect(snapshot.status).toBe("succeeded");
    expect(snapshot.document.id).toBe(target.id);
    expect(snapshot.result!.meshes).toHaveLength(2);
    for (const mesh of snapshot.result!.meshes) expect(mesh).toMatchObject({ geometrySource: "opencascade", geometryAssertions: { valid: true, solidCount: 1 } });
    expect(snapshot.result!.meshes[0].geometryAssertions!.volume).toBeCloseTo(80000, 6);
    expect(snapshot.result!.meshes[1].geometryAssertions!.volume).toBeCloseTo((80 * 50 - 4 * Math.PI * 1.6 ** 2) * 5, 6);
    expect(snapshot.result!.meshes[0].bounds.min).toEqual([-40, -25, 0]);
    expect(snapshot.result!.meshes[1].bounds.min).toEqual([-40, -25, 0]);
  }).toPass({ timeout: 30000 });
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(async () => { const s = await aiSnapshot(page); expect(s.status).toBe("succeeded"); expect(s.result!.meshes).toHaveLength(1); expect(s.document.id).toBe(before.document.id); }).toPass();
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await expect(async () => { const s = await aiSnapshot(page); expect(s.status).toBe("succeeded"); expect(s.result!.meshes).toHaveLength(2); }).toPass();
  await page.getByRole("group", { name: "Project dock tabs" }).getByRole("button", { name: "Parameters", exact: true }).click();
  const width = page.getByLabel("Parameter plate_width expression", { exact: true });
  await width.fill("100mm"); await width.press("Tab");
  await expect(async () => { const s = await aiSnapshot(page); expect(s.status).toBe("succeeded"); expect(s.result!.meshes[0].geometryAssertions!.volume).toBeCloseTo(80000, 6); expect(s.result!.meshes[1].bounds.max[0]).toBe(50); }).toPass();
  const saved = page.waitForEvent("download");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  const savedPath = await (await saved).path(); expect(savedPath).not.toBeNull(); const bytes = await readFile(savedPath!);
  const beforeOpen = await aiSnapshot(page);
  await page.locator('input[type="file"]').first().setInputFiles({ name: "assembly.pcaddoc", mimeType: "application/json", buffer: bytes });
  await expect(async () => {
    const snapshot = await aiSnapshot(page);
    expect(snapshot.session).toBeGreaterThan(beforeOpen.session);
    expect(snapshot.past).toBe(0);
    expect(snapshot.status).toBe("succeeded");
    expect(snapshot.document.id).toBe(target.id);
    expect(snapshot.document.parameters.plate_width.expression).toBe("100mm");
    expect(snapshot.result).toMatchObject({ documentId: target.id, success: true });
    expect(snapshot.result!.meshes).toHaveLength(2);
    expect(snapshot.result!.meshes[1].bounds.max[0]).toBe(50);
    for (const mesh of snapshot.result!.meshes) expect(mesh.geometrySource).toBe("opencascade");
  }).toPass({ timeout: 30000 });
  const selected = (await aiSnapshot(page)).result!.meshes[1].bodyId;
  const exported = page.waitForEvent("download");
  await page.evaluate(async (bodyId) => { const path = "/src/persistence/fileJobs.ts"; await (await import(path)).runFabrication("separate", true, [bodyId]); }, selected);
  const path = await (await exported).path(); expect(path).not.toBeNull();
  const expectedVolume = (100 * 50 - 4 * Math.PI * 1.6 ** 2) * 5;
  expect(Math.abs(stlSignedVolume(await readFile(path!)) - expectedVolume) / expectedVolume).toBeLessThan(0.005);
});
