import { expect, test, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { aiSnapshot, stlSignedVolume } from "./aiAcceptanceHelpers";

test.use({ storageState: { cookies: [], origins: [] } });
async function ready(page: Page, volume: number) {
  await expect(async () => {
    const state = await aiSnapshot(page);
    expect(state.status).toBe("succeeded");
    expect(state.result?.success).toBe(true);
    expect(state.result?.meshes).toHaveLength(1);
    const mesh = state.result!.meshes[0];
    expect(mesh.geometrySource).toBe("opencascade");
    expect(mesh.geometryAssertions).toMatchObject({ valid: true, solidCount: 1 });
    expect(mesh.geometryAssertions!.volume).toBeCloseTo(volume, 5);
  }).toPass({ timeout: 30000 });
}
async function openBox(page: Page) {
  await page.goto("/");
  await page.locator(".file-menu > summary").click();
  await page.getByRole("button", { name: "Load parametric box template", exact: true }).click();
  await ready(page, 80000);
  await page.locator(".body-row").getByRole("button").first().click();
  const label = page.getByRole("button", { name: "Edit solid thickness for Box Extrude", exact: true });
  await expect(label).toBeVisible();
  return label;
}
test("inline shared parameter choice preserves the feature formula with native preview, cancellation and durable STL", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const label = await openBox(page), before = await aiSnapshot(page);
  const parameter = before.document.parameters.depth;
  await label.press("Enter");
  const dialog = page.getByRole("dialog", { name: "Edit solid thickness", exact: true });
  const input = dialog.getByLabel("Dimension expression");
  const apply = dialog.getByRole("button", { name: "Apply dimension", exact: true });
  await expect(input).toHaveValue("depth");
  await expect(input).toBeDisabled();
  await expect(apply).toBeDisabled();
  await dialog.getByLabel("Dimension edit target").selectOption(parameter.id);
  await expect(input).toHaveValue("20mm");
  await expect(dialog.getByRole("alert")).toContainText("changed value");
  await input.fill("0mm");
  await expect(dialog.getByRole("alert")).toBeVisible();
  await expect(apply).toBeDisabled();
  await input.fill("25mm");
  await expect(dialog.getByRole("status")).toContainText("Native preview ready");
  await expect(dialog.getByText(/Shared uses of this parameter will also change/)).toBeVisible();
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  expect((await aiSnapshot(page)).past).toBe(before.past);
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  expect((await aiSnapshot(page)).document).toEqual(before.document);
  expect((await aiSnapshot(page)).past).toBe(before.past);
  await label.click();
  await dialog.getByLabel("Dimension edit target").selectOption(parameter.id);
  await input.fill("30mm");
  await input.fill("25mm");
  await expect(dialog.getByRole("status")).toContainText("Native preview ready");
  await apply.click();
  await expect(dialog).toBeHidden();
  await ready(page, 100000);
  const changed = await aiSnapshot(page), feature = changed.document.features[0];
  expect(changed.past).toBe(before.past + 1);
  expect(changed.document.parameters.depth).toMatchObject({ id: parameter.id, expression: "25mm" });
  expect(feature.id).toBe(before.document.features[0].id);
  if (feature.type !== "extrude") throw new Error("Expected box extrusion");
  expect(feature.distance).toMatchObject({ expression: "depth", parameterRefs: { depth: parameter.id } });
  expect(changed.result!.meshes[0].bounds.max[2]).toBeCloseTo(25, 6);
  await expect(label).toContainText("25 mm");
  await expect(label).toContainText("Formula: depth");
  const saving = page.waitForEvent("download");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  const project = info.outputPath("inline-shared.pcaddoc");
  await (await saving).saveAs(project);
  await page.locator('input[type="file"]').setInputFiles(project);
  await expect.poll(async () => (await aiSnapshot(page)).session).toBeGreaterThan(changed.session);
  await ready(page, 100000);
  const opened = await aiSnapshot(page);
  expect(opened.document.parameters.depth.expression).toBe("25mm");
  const reopenedFeature = opened.document.features[0];
  if (reopenedFeature.type !== "extrude") throw new Error("Expected reopened extrusion");
  expect(reopenedFeature.distance).toEqual(feature.distance);
  await page.locator(".file-menu > summary").click();
  const exporting = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export STL", exact: true }).click();
  const path = info.outputPath("inline-shared.stl");
  await (await exporting).saveAs(path);
  expect(stlSignedVolume(await readFile(path))).toBeCloseTo(100000, 2);
  expect(errors).toEqual([]);
});
