import { expect, test, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { aiSnapshot } from "./aiAcceptanceHelpers";
import { assertStepProofs, expectedStepProofs, generatePublicStep, loadStepFixture, observeStepProofs, stepTranscripts } from "./stepExportHelpers";
async function native(page: Page, depth = 5) {
  await expect(async () => {
    const state = await aiSnapshot(page);
    expect(state.status).toBe("succeeded");
    expect(state.result).toMatchObject({ success: true, documentId: state.document.id, stepExportAvailable: true });
    expect(state.result!.meshes).toHaveLength(2);
    expect(state.result!.errors).toEqual([]);
    state.result!.meshes.forEach((mesh, index) => {
      expect(mesh).toMatchObject({ geometrySource: "opencascade", geometryAssertions: { valid: true, solidCount: 1 } });
      expect(Math.abs(mesh.geometryAssertions!.volume / expectedStepProofs(depth)[index].volume - 1)).toBeLessThan(1e-8);
    });
  }).toPass({ timeout: 30000 });
}
async function changeDepth(page: Page, value: string) {
  const field = page.getByLabel("Parameter depth expression", { exact: true });
  await field.fill(value);
  await field.press("Enter");
}
test("public STEP body selection exports analytic posed solids with actual native reader volume and world bounds through edits and save/open", async ({ page }, info) => {
  await observeStepProofs(page);
  const model = await loadStepFixture(page);
  await native(page);
  await page.getByRole("button", { name: "Export STEP", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Export STEP", exact: true });
  await expect(dialog.getByRole("checkbox")).toHaveCount(2);
  await expect(dialog.getByRole("button", { name: "Download STEP file", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "Clear STEP bodies", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Generate validated STEP", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "Select all STEP bodies", exact: true }).click();
  await dialog.getByRole("checkbox", { name: "Arc rim", exact: true }).uncheck();
  await dialog.getByRole("button", { name: "Generate validated STEP", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Download STEP file", exact: true })).toBeEnabled();
  const single = (await stepTranscripts(page)).at(-1)!;
  assertStepProofs(single, [expectedStepProofs()[1]]);
  expect(single.bodyIds).toEqual([model.plateId]);
  let downloading = page.waitForEvent("download");
  await dialog.getByRole("button", { name: "Download STEP file", exact: true }).click();
  const platePath = info.outputPath("selected-hole-plate.step");
  await (await downloading).saveAs(platePath);
  const plateText = await readFile(platePath, "utf8");
  expect(plateText).toMatch(/^ISO-10303-21;/);
  expect(plateText).toMatch(/CYLINDRICAL_SURFACE/);
  expect(plateText.trimEnd()).toMatch(/END-ISO-10303-21;$/);
  let all = await generatePublicStep(page);
  const complete = (await stepTranscripts(page)).at(-1)!;
  assertStepProofs(complete);
  expect(complete.bodyIds).toEqual([model.rimId, model.plateId]);
  downloading = page.waitForEvent("download");
  await all.getByRole("button", { name: "Download STEP file", exact: true }).click();
  const assemblyPath = info.outputPath("posed-assembly.step");
  await (await downloading).saveAs(assemblyPath);
  const text = await readFile(assemblyPath, "utf8");
  expect(text).toMatch(/SI_UNIT\s*\(\s*\.MILLI\.\s*,\s*\.METRE\.\s*\)/);
  expect(text).toContain("CIRCLE");
  await changeDepth(page, "7mm");
  await native(page, 7);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await native(page, 5);
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await native(page, 7);
  downloading = page.waitForEvent("download");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  const saved = info.outputPath("posed-step-project.pcaddoc");
  await (await downloading).saveAs(saved);
  const json = JSON.parse(await readFile(saved, "utf8"));
  expect(json.parameters.depth.expression).toBe("7mm");
  expect(json.components).toEqual(model.document.components);
  expect(await readFile(saved, "utf8")).not.toMatch(/nativeStepExport|StepGeometryProof|plaincadObservedStepProofs/);
  const session = (await aiSnapshot(page)).session;
  await page.locator('input[type="file"]').first().setInputFiles(saved);
  await expect.poll(async () => (await aiSnapshot(page)).session).toBeGreaterThan(session);
  await native(page, 7);
  all = await generatePublicStep(page);
  assertStepProofs((await stepTranscripts(page)).at(-1)!, expectedStepProofs(7));
  const prepared = await page.evaluate(async () => { const path = "/src/ui/commands/stepExportState.ts"; const frame = (await import(path)).useStepExport.getState().frame; return { session: frame.session, bodyIds: frame.bodyIds, units: frame.prepared.units, roots: frame.prepared.after.length }; });
  expect(prepared).toEqual({ session: (await aiSnapshot(page)).session, bodyIds: [model.rimId, model.plateId], units: "mm", roots: 2 });
  downloading = page.waitForEvent("download");
  await all.getByRole("button", { name: "Download STEP file", exact: true }).click();
  const editedPath = info.outputPath("edited-posed-assembly.step");
  await (await downloading).saveAs(editedPath);
  expect(await readFile(editedPath, "utf8")).toMatch(/^ISO-10303-21;/);
});
test("STEP cancellation and running/prepared same-ID stale results never download or retain a usable proof", async ({ page }) => {
  await observeStepProofs(page);
  await loadStepFixture(page);
  await native(page);
  const downloads: string[] = [];
  page.on("download", download => downloads.push(download.suggestedFilename()));
  await page.getByRole("button", { name: "Export STEP", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Export STEP", exact: true });
  let creation = page.waitForEvent("worker", { predicate: worker => worker.url().includes("stepExportWorker") });
  await dialog.getByRole("button", { name: "Generate validated STEP", exact: true }).click();
  let worker = await creation, closed = worker.waitForEvent("close");
  await expect(dialog.getByRole("button", { name: "Download STEP file", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "Cancel STEP export", exact: true }).click();
  await closed;
  await expect(dialog).toBeHidden();
  expect(downloads).toEqual([]);
  expect(await stepTranscripts(page)).toEqual([]);
  await page.getByRole("button", { name: "Export STEP", exact: true }).click();
  creation = page.waitForEvent("worker", { predicate: next => next.url().includes("stepExportWorker") });
  await dialog.getByRole("button", { name: "Generate validated STEP", exact: true }).click();
  worker = await creation;
  closed = worker.waitForEvent("close");
  await page.evaluate(async () => {
    const storePath = "/src/state/useCadStore.ts", exportPath = "/src/ui/commands/stepExportState.ts";
    const store = (await import(storePath)).useCadStore;
    if (!(await import(exportPath)).useStepExport.getState().frame?.busy)
      throw new Error("Expected a live STEP job before replacing its document");
    store.getState().setDocument({ ...store.getState().history.present });
  });
  await closed;
  await expect(dialog.getByRole("button", { name: "Download STEP file", exact: true })).toBeDisabled();
  await expect(dialog.getByRole("alert").first()).toContainText(/model changed/i);
  expect(downloads).toEqual([]);
  await dialog.getByRole("button", { name: "Cancel STEP export", exact: true }).click();
  await native(page);
  await generatePublicStep(page);
  assertStepProofs((await stepTranscripts(page)).at(-1)!);
  await page.evaluate(async () => {
    const storePath = "/src/state/useCadStore.ts", commandPath = "/src/ui/commands/stepExportJob.ts";
    const store = (await import(storePath)).useCadStore;
    store.getState().setDocument({ ...store.getState().history.present });
    // Invoke the same guarded download handler after replacement, even though UI availability disables it.
    (await import(commandPath)).downloadPreparedStep();
  });
  await expect(dialog.getByRole("button", { name: "Download STEP file", exact: true })).toBeDisabled();
  const remaining = await page.evaluate(async () => { const path = "/src/ui/commands/stepExportState.ts"; const frame = (await import(path)).useStepExport.getState().frame; return { prepared: Boolean(frame?.prepared), error: frame?.error }; });
  expect(remaining.prepared).toBe(false);
  expect(remaining.error).toMatch(/changed after STEP validation/i);
  expect(downloads).toEqual([]);
  await dialog.getByRole("button", { name: "Cancel STEP export", exact: true }).click();
});
test("a real STEP worker load failure is actionable, cannot download, and can be retried successfully", async ({ page }) => {
  await observeStepProofs(page);
  await loadStepFixture(page);
  await native(page);
  const downloads: string[] = [];
  page.on("download", download => downloads.push(download.suggestedFilename()));
  // Abort the worker executable, allowing its ESM factory to load so retry is real.
  const workerScript = (url: URL) => url.pathname.includes("stepExportWorker") && url.searchParams.has("worker_file");
  const blocked: string[] = [];
  await page.route(workerScript, route => { blocked.push(route.request().url()); return route.abort("failed"); });
  await page.getByRole("button", { name: "Export STEP", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Export STEP", exact: true });
  await dialog.getByRole("button", { name: "Generate validated STEP", exact: true }).click();
  await expect(dialog.getByRole("alert")).toHaveCount(1);
  await expect(dialog.getByRole("alert")).toHaveText("Background operation failed.");
  expect(blocked).toHaveLength(1);
  await expect(dialog.getByRole("button", { name: "Download STEP file", exact: true })).toBeDisabled();
  expect(downloads).toEqual([]);
  expect(await stepTranscripts(page)).toEqual([]);
  await page.unroute(workerScript);
  await dialog.getByRole("button", { name: "Generate validated STEP", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Download STEP file", exact: true })).toBeEnabled();
  assertStepProofs((await stepTranscripts(page)).at(-1)!);
  await dialog.getByRole("button", { name: "Cancel STEP export", exact: true }).click();
  expect(downloads).toEqual([]);
});
