import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { SECURITY_HEADERS } from "../deployment/securityHeaders";
import { assertStepProofs, loadStepFixture, observeStepProofs, stepTranscripts } from "../e2e/stepExportHelpers";
import { inspectPngDownload } from "../e2e/pngDownload";
test("built export hub hands off native STEP and PNG under production security headers", async ({ page }, info) => {
  const errors: string[] = [], violations: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.exposeFunction("hubCspViolation", (directive: string) => violations.push(directive));
  await page.addInitScript(() => document.addEventListener("securitypolicyviolation", event => {
    void (window as unknown as { hubCspViolation(directive: string): Promise<void> }).hubCspViolation(event.effectiveDirective);
  }));
  await observeStepProofs(page);
  const response = await page.goto("/");
  if (!response) throw new Error("Production navigation returned no response.");
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) expect(response.headers()[name.toLowerCase()]).toBe(value);
  await loadStepFixture(page);
  await page.getByRole("button", { name: "Save or export", exact: true }).click();
  let hub = page.getByRole("dialog", { name: "Save or export", exact: true });
  await expect(hub.getByRole("radio")).toHaveCount(5);
  await hub.getByRole("radio", { name: /Other CAD/ }).check();
  await hub.getByRole("button", { name: "Choose parts for STEP" }).click();
  const step = page.getByRole("dialog", { name: "Export STEP", exact: true });
  await step.getByRole("button", { name: "Generate validated STEP" }).click();
  await expect(step.getByRole("button", { name: "Download STEP file" })).toBeEnabled();
  const proof = (await stepTranscripts(page)).at(-1);
  if (!proof) throw new Error("Native STEP export returned no geometry proof.");
  assertStepProofs(proof);
  let download = page.waitForEvent("download");
  await step.getByRole("button", { name: "Download STEP file" }).click();
  const path = info.outputPath("hub-production.step");
  await (await download).saveAs(path);
  expect(await readFile(path, "utf8")).toMatch(/^ISO-10303-21;/);
  await page.getByRole("button", { name: "Save or export", exact: true }).click();
  hub = page.getByRole("dialog", { name: "Save or export", exact: true });
  await hub.getByRole("radio", { name: /Image \(\.png\)/ }).check();
  download = page.waitForEvent("download");
  await hub.getByRole("button", { name: "Download PNG" }).click();
  await inspectPngDownload(page, await download, info.outputPath("hub-production.png"));
  expect(violations).toEqual([]);
  expect(errors).toEqual([]);
});
